moving1: movingTheManWithUdp.c
	gcc -o movingTheManWithUdp movingTheManWithUdp.c -IC:\MinGW\include\SDL2 -lmingw32 -lSDL2main -lSDL2 -lSDL2_net -lSDL2_image
moving2: movingTwoMenWithUdp.c
	gcc -o movingTwoMenWithUdp movingTwoMenWithUdp.c -IC:\MinGW\include\SDL2 -lmingw32 -lSDL2main -lSDL2 -lSDL2_net -lSDL2_image
moving3: movingTwoMenWithUdpAndStruct.c
	gcc -o movingTwoMenWithUdpAndStruct movingTwoMenWithUdpAndStruct.c -IC:\MinGW\include\SDL2 -lmingw32 -lSDL2main -lSDL2 -lSDL2_net -lSDL2_image
