start UDPserver.exe        
:: ^START GÖR ATT DEN GÅR VIDARE TILL NÄSTA "RAD" MEDAN .EXE-FILEN KÖRS
start main.exe                   
:: ^INGEN START BETYDER ATT DEN VÄNTAR MED NÄSTA RAD TILLS MAN STÄNGT NER .EXE FILEN
main.exe                   
:: ^INGEN START BETYDER ATT DEN VÄNTAR MED NÄSTA RAD TILLS MAN STÄNGT NER .EXE FILEN
taskkill /im UDPserver.exe 
:: ^STÄNGER NER SERVERN EFTER MAN STÄNGT SIN CLIENT
taskkill /im main.exe 
:: ^STÄNGER NER SERVERN EFTER MAN STÄNGT SIN CLIENT
